#!/usr/bin/env python3
"""mdbook preprocessor that renders spec anchors.

A rule that the compiler enforces is marked in the prose with::

    {{#spec SAME_SCOPE_REDECLARATION}}

which becomes a small labelled anchor the reader can link to
(``#spec-SAME_SCOPE_REDECLARATION``), and — when ``spec-links.json`` is present
next to ``book.toml`` — the list of source locations that implement the rule.

That json is generated by ``scripts/spec_links.py`` in the repository root,
which is also the thing that fails when a marker and the code disagree. Both
sides are optional at *build* time: with no json the anchor still renders, just
without the implementation links, so the book builds fine in a bare Docker
context.

Markers inside code blocks (fenced or inline) are left alone, so documentation
about this convention can show the syntax literally.

spec-links: ignore
"""
import html
import json
import re
import sys
from pathlib import Path

MARKER_RE = re.compile(r'\{\{#spec\s+([A-Za-z0-9_]+)\s*\}\}')
CODE_FENCE_RE = re.compile(r'(?ms)^(`{3,}|~{3,})[^\n]*\n.*?^\1[ \t]*$')
INLINE_CODE_RE = re.compile(r'(`+)(?!`).*?\1')

LINKS_FILE = 'spec-links.json'


def _stash(text, pattern, blocks, tag):
    def keep(a_match):
        blocks.append(a_match.group(0))
        return f'\x00{tag}{len(blocks) - 1}\x00'

    return pattern.sub(keep, text)


def _unstash(text, blocks, tag):
    return re.sub(rf'\x00{tag}(\d+)\x00', lambda m: blocks[int(m.group(1))], text)


def load_links(root):
    """Read the generated code locations; missing or broken json is not fatal."""
    path = Path(root) / LINKS_FILE
    try:
        data = json.loads(path.read_text(encoding='utf-8'))
    except (OSError, ValueError):
        return {}, ''
    return data.get('anchors', {}), data.get('source_url', '')


def render(an_id, sites, source_url):
    anchor = f'spec-{an_id}'
    parts = [
        f'<span class="tel-spec" id="{anchor}">',
        f'<a class="tel-spec-id" href="#{anchor}" '
        f'title="Spec anchor: the implementation refers to this rule by id">{an_id}</a>',
    ]
    links = []
    for site in sites:
        path, line = site.get('path', ''), site.get('line', 0)
        label = html.escape(f'{path}:{line}')
        title = html.escape(site['note']) if site.get('note') else ''
        title_attr = f' title="{title}"' if title else ''
        if source_url:
            href = html.escape(source_url.format(path=path, line=line), quote=True)
            links.append(f'<a href="{href}"{title_attr}>{label}</a>')
        else:
            links.append(f'<span{title_attr}>{label}</span>')
    if links:
        parts.append('<span class="tel-spec-impl">implemented in ' + ', '.join(links) + '</span>')
    parts.append('</span>')
    return ''.join(parts)


def process(text, anchors, source_url):
    if '{{#spec' not in text:
        return text
    fences, inlines = [], []
    text = _stash(text, CODE_FENCE_RE, fences, 'F')
    text = _stash(text, INLINE_CODE_RE, inlines, 'I')
    text = MARKER_RE.sub(
        lambda m: render(m.group(1), anchors.get(m.group(1), []), source_url), text)
    text = _unstash(text, inlines, 'I')
    text = _unstash(text, fences, 'F')
    return text


def walk(items, anchors, source_url):
    for item in items:
        if isinstance(item, dict) and 'Chapter' in item:
            chapter = item['Chapter']
            chapter['content'] = process(chapter['content'], anchors, source_url)
            if chapter.get('sub_items'):
                walk(chapter['sub_items'], anchors, source_url)


def main():
    if len(sys.argv) > 1 and sys.argv[1] == 'supports':
        sys.exit(0)
    ctx, book = json.load(sys.stdin)
    anchors, source_url = load_links(ctx['root'])
    walk(book.get('sections', []), anchors, source_url)
    json.dump(book, sys.stdout)


if __name__ == '__main__':
    main()
